# db(Postgres),app(Django)のコンテナを作成
services:
  db:
    # コンテナ名をpostgresに設定
    container_name: postgres
    # PostgreSQLのDockerfileをビルドする
    build:
      # ビルドコンテキストはカレントディレクトリ
      # postgreSQLのイメージはDockerfileに記載
      context: .
      dockerfile: containers/postgres/Dockerfile
    # M2チップでも動くように
    # Intel Macの場合あってもなくても動く
    # 動作の様子を見て削除も検討
    platform: linux/x86_64
    # DBのボリュームを指定
    # ローカルの/data/dbをコンテナの/var/lib/postgresql/dataにマウントする
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    # ヘルスチェック
    healthcheck:
      test: pg_isready -U "${POSTGRES_USER:-postgres}" || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    # コンテナ内の環境変数を.envを使って設定
    env_file:
      - .env
  app:
    # コンテナ名をappに設定
    container_name: app
    # DjangoのDockerfileをビルドする
    build:
      # ビルドコンテキストはカレントディレクトリ
      context: .
      dockerfile: containers/django/Dockerfile
    # ボリュームを指定
    # ローカルのカレントディレクトリをコンテナの/codeにマウントする
    # ローカルの/staticをコンテナの/staticにマウントする
    volumes:
      - .:/code
      - ./static:/static
    # ローカルの8000番ポートとコンテナの8000番ポートをつなぐ
    ports:
      - "8000:8000"
    # シェルスクリプトを実行
    command: sh -c "/usr/local/bin/entrypoint.sh"
    # コンテナ内の環境変数を.envを使って設定
    env_file:
      - .env
    # 先にdbを起動してからappを起動する
    depends_on:
      db:
        condition: service_healthy
volumes:
  db_data:
  static:
